// Auth Actions
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const REFRESH = 'REFRESH';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAILURE = 'REFRESH_FAILURE';

// Profile Actions
export const LOAD_PROFILES = 'LOAD_PROFILES';
export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS';
export const LOAD_PROFILES_FAILURE = 'LOAD_PROFILES_FAILURE';
export const LOAD_EXTENDED_PROFILE = 'LOAD_EXTENDED_PROFILE';
export const LOAD_EXTENDED_PROFILE_SUCCESS = 'LOAD_EXTENDED_PROFILE_SUCCESS';
export const LOAD_EXTENDED_PROFILE_FAILURE = 'LOAD_EXTENDED_PROFILE_FAILURE';

// Location Actions
export const LOAD_LOCATION = 'LOAD_LOCATION';
export const LOAD_LOCATION_SUCCESS = 'LOAD_LOCATION_SUCCESS';
export const LOAD_LOCATION_FAILURE = 'LOAD_LOCATION_FAILURE';
export const LOAD_LOCATION_MEMBERS = 'LOAD_LOCATION_MEMBERS';
export const LOAD_LOCATION_MEMBERS_SUCCESS = 'LOAD_LOCATION_MEMBERS_SUCCESS';
export const LOAD_LOCATION_MEMBERS_FAILURE = 'LOAD_LOCATION_MEMBERS_FAILURE';

// Header Actions
export const TOGGLE_DISPLAY_HEADER = 'TOGGLE_DISPLAY_HEADER';

// Search Actions
export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

// Explore actions
export const EXPLORE = 'EXPLORE';
export const EXPLORE_SUCCESS = 'EXPLORE_SUCCESS';
export const EXPLORE_FAILURE = 'EXPLORE_FAILURE';
export const CLEAR_EXPLORE_RESULTS = 'CLEAR_EXPLORE_RESULTS';

// Team actions
export const LOAD_EXTENDED_TEAM = 'LOAD_EXTENDED_TEAM';
export const LOAD_EXTENDED_TEAM_SUCCESS = 'LOAD_EXTENDED_TEAM_SUCCESS';
export const LOAD_EXTENDED_TEAM_FAILURE = 'LOAD_EXTENDED_TEAM_FAILURE';
export const LOAD_TEAM_MEMBERS = 'LOAD_TEAM_MEMBERS';
export const LOAD_TEAM_MEMBERS_SUCCESS = 'LOAD_TEAM_MEMBERS_SUCCESS';
export const LOAD_TEAM_MEMBERS_FAILURE = 'LOAD_TEAM_MEMBERS_FAILURE';
