// Auth Actions
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Profile Actions
export const LOAD_PROFILES = 'LOAD_PROFILES';
export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS';
export const LOAD_PROFILES_FAILURE = 'LOAD_PROFILES_FAILURE';
export const LOAD_EXTENDED_PROFILE = 'LOAD_EXTENDED_PROFILE';
export const LOAD_EXTENDED_PROFILE_SUCCESS = 'LOAD_EXTENDED_PROFILE_SUCCESS';
export const LOAD_EXTENDED_PROFILE_FAILURE = 'LOAD_EXTENDED_PROFILE_FAILURE';