// Auth Actions
export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const GET_AUTHENTICATION_INSTRUCTIONS = 'GET_AUTHENTICATION_INSTRUCTIONS';
export const GET_AUTHENTICATION_INSTRUCTIONS_SUCCESS = 'GET_AUTHENTICATION_INSTRUCTIONS_SUCCESS';
export const GET_AUTHENTICATION_INSTRUCTIONS_FAILURE = 'GET_AUTHENTICATION_INSTRUCTIONS_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const REFRESH = 'REFRESH';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAILURE = 'REFRESH_FAILURE';
export const REQUEST_ACCESS = 'REQUEST_ACCESS';
export const REQUEST_ACCESS_SUCCESS = 'REQUEST_ACCESS_SUCCESS';
export const REQUEST_ACCESS_FAILURE = 'REQUEST_ACCESS_FAILURE';

// Profile Actions
export const LOAD_PROFILES = 'LOAD_PROFILES';
export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS';
export const LOAD_PROFILES_FAILURE = 'LOAD_PROFILES_FAILURE';
export const LOAD_EXTENDED_PROFILE = 'LOAD_EXTENDED_PROFILE';
export const LOAD_EXTENDED_PROFILE_SUCCESS = 'LOAD_EXTENDED_PROFILE_SUCCESS';
export const LOAD_EXTENDED_PROFILE_FAILURE = 'LOAD_EXTENDED_PROFILE_FAILURE';

// Update Profile Actions
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

// Location Actions
export const LOAD_LOCATION = 'LOAD_LOCATION';
export const LOAD_LOCATION_SUCCESS = 'LOAD_LOCATION_SUCCESS';
export const LOAD_LOCATION_FAILURE = 'LOAD_LOCATION_FAILURE';
export const LOAD_LOCATION_MEMBERS = 'LOAD_LOCATION_MEMBERS';
export const LOAD_LOCATION_MEMBERS_SUCCESS = 'LOAD_LOCATION_MEMBERS_SUCCESS';
export const LOAD_LOCATION_MEMBERS_FAILURE = 'LOAD_LOCATION_MEMBERS_FAILURE';

// Update Location Actions
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAILURE = 'UPDATE_LOCATION_FAILURE';

// Header Actions
export const TOGGLE_DISPLAY_HEADER = 'TOGGLE_DISPLAY_HEADER';

// Search Actions
export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const VIEW_SEARCH_RESULT = 'VIEW_SEARCH_RESULT';
export const NO_SEARCH_RESULTS = 'NO_SEARCH_RESULTS';
export const NO_SEARCH_RESULTS_SUCCESS = 'NO_SEARCH_RESULTS_SUCCESS';
export const NO_SEARCH_RESULTS_FAILURE = 'NO_SEARCH_RESULTS_FAILURE';

// Explore actions
export const EXPLORE = 'EXPLORE';
export const EXPLORE_SUCCESS = 'EXPLORE_SUCCESS';
export const EXPLORE_FAILURE = 'EXPLORE_FAILURE';

// Team actions
export const LOAD_EXTENDED_TEAM = 'LOAD_EXTENDED_TEAM';
export const LOAD_EXTENDED_TEAM_SUCCESS = 'LOAD_EXTENDED_TEAM_SUCCESS';
export const LOAD_EXTENDED_TEAM_FAILURE = 'LOAD_EXTENDED_TEAM_FAILURE';
export const LOAD_TEAM_MEMBERS = 'LOAD_TEAM_MEMBERS';
export const LOAD_TEAM_MEMBERS_SUCCESS = 'LOAD_TEAM_MEMBERS_SUCCESS';
export const LOAD_TEAM_MEMBERS_FAILURE = 'LOAD_TEAM_MEMBERS_FAILURE';
export const CLEAR_TEAM_MEMBERS_CACHE = 'CLEAR_TEAM_MEMBERS_CACHE';

// Update Team Actions
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAILURE = 'UPDATE_TEAM_FAILURE';

// Device Actions
export const DEVICE_RESIZED = 'DEVICE_RESIZED';

// Billing Actions
export const STORE_TOKEN = 'STORE_TOKEN';
export const STORE_TOKEN_SUCCESS = 'STORE_TOKEN_SUCCESS';
export const STORE_TOKEN_FAILURE = 'STORE_TOKEN_FAILURE';

// Media Upload Actions
export const MEDIA_UPLOAD = 'MEDIA_UPLOAD';
export const MEDIA_UPLOAD_SUCCESS = 'MEDIA_UPLOAD_SUCCESS';
export const MEDIA_UPLOAD_FAILURE = 'MEDIA_UPLOAD_FAILURE';

// Create Post Actions
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

// Update Post Actions
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';

// Delete Post Actions
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

// Get Post Actions
export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

// Get Posts Actions
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

// Clear Posts Action
export const CLEAR_POSTS_CACHE = 'CLEAR_POSTS_CACHE';

// File Upload Actions
export const FILE_UPLOAD = 'FILE_UPLOAD';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILURE = 'FILE_UPLOAD_FAILURE';

// Delete file
export const DELETE_LOCAL_FILE = 'DELETE_LOCAL_FILE';
